version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/src/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 10

  - package-ecosystem: "docker"
    directory: "/src/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 10
