version: "3"

services:
  db:
    image: mariadb:lts-jammy
    container_name: db
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - volume-db:/var/lib/mysql
    ports:
      - "3306:3306"
    expose:
      - "3306"

  web:
    container_name: web
    build:
      context: src
    expose:
      - "8000"

    environment:
      - VIRTUAL_HOST=${WEB_VIRTUAL_HOST}
      - LETSENCRYPT_HOST=${WEB_LETSENCRYPT_HOST}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}

      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}
      - SECRET_KEY=${WEB_SECRET_KEY}
      - DEBUG='False'
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - IS_PROD=1
      - OPENAI_API_KEY=${WEB_OPENAI_API_KEY}
      - WEB_CRYPTOGRAPHY_KEY=${WEB_CRYPTOGRAPHY_KEY}
    ports:
      - "8000:8000"
    volumes:
      - volume-web-static:/_static
    depends_on:
      - db

  nginx-proxy:
    image: nginxproxy/nginx-proxy:latest
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes_from:
      - web
    volumes:
      - /etc/nginx/certs
      - /etc/nginx/vhost.d
      - /usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro

  nginx-letsencrypt:
    image: nginxproxy/acme-companion:latest
    container_name: nginx-letsencrypt
    environment:
      - DEFAULT_EMAIL=${DEFAULT_EMAIL}
    volumes_from:
      - nginx-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

volumes:
  volume-db:
  volume-web-static: