version: "3"

services:
  doc:
    container_name: doc
    build:
      context: docs
    environment:
      - VIRTUAL_HOST=${DOC_VIRTUAL_HOST}
      - LETSENCRYPT_HOST=${DOC_LETSENCRYPT_HOST}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
    ports:
      - ${DOC_PORT}:${DOC_PORT}

  db:
    image: mariadb:lts-jammy
    container_name: db
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - volume-db:/var/lib/mysql
    ports:
      - ${DB_PORT}:${DB_PORT}

  web:
    container_name: web
    build:
      context: src
    environment:
      - VIRTUAL_HOST=${WEB_VIRTUAL_HOST}
      - LETSENCRYPT_HOST=${WEB_LETSENCRYPT_HOST}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}

      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}

      - SECRET_KEY=${DJANGO_SECRET_KEY}
      - DEBUG='False'

      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}

      - IS_PROD=1
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    ports:
      - ${WEB_PORT}:${WEB_PORT}
    depends_on:
      - db

  nginx-proxy:
    image: nginxproxy/nginx-proxy:latest
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - volume-nginx-certs:/etc/nginx/certs
      - volume-nginx-vhost:/etc/nginx/vhost.d
      - volume-nginx-html:/usr/share/nginx/html

      - /var/run/docker.sock:/tmp/docker.sock:ro

  nginx-letsencrypt:
    image: nginxproxy/acme-companion:latest
    container_name: nginx-letsencrypt
    environment:
      - DEFAULT_EMAIL=${DEFAULT_EMAIL}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - volume-nginx-acme:/etc/acme.sh
    depends_on:
      - nginx-proxy

volumes:
  volume-db:
  volume-nginx-certs:
  volume-nginx-vhost:
  volume-nginx-html:
  volume-nginx-acme:
