Your Project Name: rest_api.views Namespace Reference
rest_api.views Namespace Reference
Functions
str get_prompt (str topic, str details)
dict get_data (str topic, str details)
def index (request)
def create_ppt (request)
Variables
logger = logging.getLogger(__name__)
level
INFO
format
openai_api_key = os.getenv('OPENAI_API_KEY')
string openai_model = 'gpt-3.5-turbo'
dictionary headers
dictionary system_role_content = {"role": "system", "content": "You are making ppt for the class, skilled in making index and its belongings.showing only the title and content of the slides without other flowery words or summary or etc."}
string url = "https://api.openai.com/v1/chat/completions"
Function Documentation
create_ppt()
def rest_api.views.create_ppt (request)
Definition at line 66 of file views.py.
References rest_api.views.get_data().
get_data()
dict rest_api.views.get_data (str topic, str details)
Definition at line 47 of file views.py.
References rest_api.views.get_prompt().
Referenced by rest_api.views.create_ppt().
get_prompt()
str rest_api.views.get_prompt (str topic, str details)
Definition at line 28 of file views.py.
Referenced by rest_api.views.get_data().
index()
def rest_api.views.index (request)
Definition at line 59 of file views.py.
Variable Documentation
format
rest_api.views.format
Definition at line 12 of file views.py.
headers
dictionary rest_api.views.headers
Initial value:
 =  {
     "Content-Type": "application/json",
     "Authorization": f"Bearer {openai_api_key}"
 }
Definition at line 17 of file views.py.
INFO
rest_api.views.INFO
Definition at line 12 of file views.py.
level
rest_api.views.level
Definition at line 12 of file views.py.
logger
rest_api.views.logger = logging.getLogger(__name__)
Definition at line 11 of file views.py.
openai_api_key
rest_api.views.openai_api_key = os.getenv('OPENAI_API_KEY')
Definition at line 15 of file views.py.
openai_model
string rest_api.views.openai_model = 'gpt-3.5-turbo'
Definition at line 16 of file views.py.
system_role_content
dictionary rest_api.views.system_role_content = {"role": "system", "content": "You are making ppt for the class, skilled in making index and its belongings.showing only the title and content of the slides without other flowery words or summary or etc."}
Definition at line 22 of file views.py.
url
string rest_api.views.url = "https://api.openai.com/v1/chat/completions"
Definition at line 23 of file views.py.