name: Build Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Docker Build Test
        run: docker build -t test_image ./src

      - name: Docker Build Test Echo Logs
        run: echo "Build tests completed"
